name: deeprl
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - python=3.9
  - pip:
    - jax
    - dm-haiku
    - rlax
    - pytest
    - optax
    - gym
    - pygame
    - mujoco-py<2.2,>=2.1
    - xlsxwriter
